### PR TITLE
update for PHP client - now contains authentication values

### PR DESCRIPTION
**Pull request by Amy1612**
I have made the changes from the old PHP client for authentication. I came across some warnings, the first I fixed if statement needed {} but there was also:

1.  Method length is 24 lines (20 allowed) 

2. Too Many Nested Blocks in Function Declaration
      -It is a good practice to introduce a new function rather than to use more nested blocks.
Just wondering if these were left for a reason?

### CODE REVIEW

**Comment by leonatherton** [comment]
Apologies for the delay in getting to this.

I think those inspections are just defaults from your IDE (not something we've defined).

Where possible we would like to follow language conventions, particularly for public API so that developers who are familiar with the language get something they're familiar with. I don't consider myself a PHP expert and would defer to something like https://phptherightway.com/

Have you tested the new authentication stuff is working too?

**Comment by KieranFrance** [comment]
I believe Leon is correct about the inspections.

**Comment by KieranFrance** [comment]
If we can confirm the changes are working as intended the can merge the tests.

**Comment by KieranFrance** [comment]
@Amy1612 Looks good. Can you merge the pull request and release to the package manager

**Comment by daniel-warren** [comment]
Just a quick note from using these changes on my new environment, when trying to run the file I got the following warning:

> PHP Fatal error:  Uncaught Error: Undefined class constant 'KEY_USERNAME' in C:\Users\idrsolutions\Documents\workspace\project-cluster\idrsolutions-php-client\src\IDRCloudClient.php:89

Which was resolved by adding the following to line 19/20
`const KEY_USERNAME = 'username';`
`const KEY_PASSWORD = 'password';`

@Amy1612 - As these are your changes, I may have missed something, so your input would be appreciated.

**Comment by Amy1612** [comment]
no that would be correct, I would think its my mistake sorry

**Pull request merged**
